config/routes.rb
Rails.application.routes.draw do
  root "docks#new"
  resources :docks, except: [:edit]

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dock.rb
class Dock < ApplicationRecord
  attribute :title, :string
  attribute :format, :string
  belongs_to :user
  has_many_attached :files
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many  :docks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docks_controller.rb
class DocksController < ApplicationController
  before_action :set_dock, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]


  # GET /docks or /docks.json
  def index
    @total_file = 0
    @docks = Dock.all
  end

  # GET /docks/1 or /docks/1.json
  def show
    @dock = Dock.find(params[:id])
    ActiveStorage::Current.url_options = {
      host: request.base_url,
      protocol: request.protocol
    }
  end

  # GET /docks/new
  def new
    @dock = Dock.new
  end

  # GET /docks/1/edit
  def edit
  end

  # POST /docks or /docks.json
  def create
    files = Array(params[:dock][:files])
    if files.length <= 1
      redirect_to new_dock_path, notice: "please select a file"
    else
      files.each do |file|
        next if file.blank?
        @dock = Dock.new(dock_params)
        @dock.files.attach(file)
        @dock.title = file.original_filename if file.respond_to?(:original_filename)
        @dock.format = file.content_type.to_s if file.respond_to?(:content_type)
        
        @dock.save
      end
        respond_to do |format|
          if @dock.persisted?
            format.html { redirect_to dock_url(@dock)}
            format.json { render :show, status: :created, location: @dock }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @dock.errors, status: :unprocessable_entity }
          end
        end
      end
  end

  # PATCH/PUT /docks/1 or /docks/1.json
  def update
    respond_to do |format|
      if @dock.update(dock_params)
        format.html { redirect_to dock_url(@dock)}
        format.json { render :show, status: :ok, location: @dock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docks/1 or /docks/1.json
  def destroy
    @dock.destroy

    respond_to do |format|
      format.html { redirect_to docks_url, notice: "Dock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dock
      @dock = Dock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dock_params
      params.require(:dock).permit(:title, :user_id, :format, docks: [])
    end

    def correct_user
      @dock = Dock.find(params[:id])
      if current_user.id != @dock.user_id
        redirect_to new_dock_path
      end
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docks_helper.rb
module DocksHelper
end

app/views/docks/_attachment.html.erb
<% if dock.files.attached? %>
  <% dock.files.each do |file| %>
    <div class="row">
      <% if file.image? %>
        <%= image_tag(file) %>
      <% elsif file.video? %>
        <%= video_tag(file, controls: true) %>
      <% elsif file.audio? %>
        <%= audio_tag(file, controls: true) %>
      <% elsif file.blob.content_type == "application/pdf" %>
        <%= link_to file.filename, url_for(file), target: "_blank" %>
      <% elsif file.blob.content_type == "text/csv" %>
        <%= file.filename %> (CSV file)
      <% else %>
        <%= link_to file.filename, url_for(file), target: "_blank" %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/docks/_dock.html.erb
<% if dock.files.attached? %>
  <% dock.files.each do |file| %>
    <div class="row">
    <%= link_to file.filename, url_for(file), target: "_blank" %>
    </div>
  <% end %>
<% end %>

app/views/docks/_form.html.erb
<div style="display: flex; justify-content: center; align-items: center;">
<%= form_with(model: dock) do |form| %>
  <% if dock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dock.errors.count, "error") %> prohibited this dock from being saved:</h2>

      <ul>
        <% dock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if current_user %>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
  

  <div class="d-flex justify-content-center align-items-center">
    <%= form.file_field :files, multiple: true, name: 'dock[files][]', class: 'form-control' %>
  </div>

</br>
</br>
  <div style="text-align: center; padding-top: 20px;">
    <%= form.submit('Upload', class: 'btn btn-outline-info') %>
  </div>

  <% end %>
<% end %>
</div>

app/views/docks/edit.html.erb
<h1>Editing dock</h1>

<%= render "form", dock: @dock %>

<br>

<div>
  <%= link_to "Show this dock", @dock %> |
  <%= link_to "Back to docks", docks_path %>
</div>

app/views/docks/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
<% @docks.each do |dock| %>
  <% if dock.user_id == current_user.id %>
  <% @total_file += 1 %>
  <div class="col-sm-3">
    <div class="card bg-dark text-info" style="border-radius: 1rem;">
    <h5 class="card-header text-info text-center">Uploaded at: <%= dock.created_at %></h5>
      <div class="card-body">
        <div class="d-flex justify-content-center align-items-center">
          <i class="fa-regular fa-circle-down fa-2x" style="color: info;"></i>
        </div>
        <h5 class="card-title text-info text-center"><%= render dock %></h5>
        <div class="text-center">
          <%= link_to "Show File", dock, class: "btn btn-outline-info" %>
        </div>
      </div>
    </div>
    <br/>
  </div>
  <% end %>
<% end %>

<% if @total_file == 0 %>
  <div style="text-align: center; font-size: 100px; padding-top: 40px;">
  <%= link_to new_dock_path, class: "your-link-class" do %><i class="fa-solid fa-file-circle-plus"></i><% end %>

  </div>
<% end %>

</div>

app/views/docks/new.html.erb
<% if user_signed_in? %>

<div>
<div style="text-align: center; padding-top: 70px;">
  <h1>Upload Files</h1>
</div>

<div style="text-align: center;">
  <i style="font-size: 200px;" class="fa-solid fa-cloud-arrow-down"></i>
</div>

  <div class="file-upload-wrapper">
  <%= render "form", dock: @dock %>
  </div>
  <div>
    <%= link_to "Back to Files", docks_path, class: "btn btn-outline-info" %>
  </div>
</div>
<% else %>


<div style="text-align: center; padding-top: 120px;">
    <i style="font-size: 200px;" class="fa-solid fa-cloud-arrow-down"></i>
</div>



<figure class="text-center">
    <blockquote class="blockquote">
                <h1 class="card-title"><strong>My DropBox</strong></h1><br/>
                <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-outline-info" %>
                <%= link_to "Login", new_user_session_path, class:"btn btn-outline-info" %>    
    </blockquote>
</figure> 

<% end %>

app/views/docks/show.html.erb
<body>
  <p style="color: green"><%= notice %></p>
  <div class="text-center">
    <% if @dock.files.attached? %>
      <% @dock.files.each do |file| %>
        <div class="row">
          <% if file.content_type.start_with?('image/') %>
            <div>
              <i class="fa-regular fa-images" style="font-size: 80px;"></i>
            </div>
            <div style="padding-top: 20px;">
              <%= link_to image_tag(file, width: 200, height: 200), rails_blob_path(file, disposition: "attachment"), download: file.filename %>
            </div>

          <% elsif  file.content_type.start_with?('application/pdf')%>
            <div>
              <i class="fa-regular fa-file-pdf" style="font-size: 80px;"></i>
            </div>
            <div style="padding-top: 20px;">
              <iframe src="<%= rails_blob_path(file, disposition: "inline") %>" style="width: 100%; height: 500px;"></iframe>
            </div>

          <% elsif file.content_type.start_with?('text/csv') || file.content_type.start_with?('text/xlxs') %>
            <div>
              <i class="fa-solid fa-file-csv" style="font-size: 80px;"></i>
            </div>
            <div style="padding-top: 20px;">
              <%= link_to file.filename, rails_blob_path(file, disposition: "attachment"), class: "btn btn-primary", download: file.filename %>
            </div>
            <div style="padding-top: 20px;">
              <table class="table table-striped">
                <thead>
                  <% CSV.parse(file.download, headers: true).headers.each do |header| %>
                    <th><%= header %></th>
                  <% end %>
                </thead>
                <tbody>
                  <% CSV.parse(file.download, headers: true).each do |row| %>
                    <tr>
                      <% row.each do |column| %>
                        <td><%= column[1] %></td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% elsif file.content_type.start_with?('video/') %>
            <div>
              <video width="400" controls>
                <source src="<%= url_for(file) %>" type="<%= file.content_type %>">
                Your browser does not support HTML5 video.
              </video>
            </div>
            <div style="padding-top: 20px;">
              <%= link_to file.filename, rails_blob_path(file, disposition: "attachment"), class: "btn btn-primary", download: file.filename %>
            </div>


            <% elsif file.content_type.start_with?('text/plain') %>
            <div>
              <i class="fa-solid fa-file-alt" style="font-size: 80px;"></i>
            </div>
            <div style="padding-top: 20px;">
              <pre><%= file.download.force_encoding('UTF-8') %></pre>
            </div>
            <div style="padding-top: 20px;">
              <%= link_to "Download", rails_blob_path(file, disposition: "attachment"), class: "btn btn-primary", download: file.filename %>
            </div>

            <% elsif file.content_type.start_with?('audio/') %>
            <div style="padding-bottom: 30px;">
              <i class="fa-solid fa-headphones" style="font-size: 80px;"></i>
            </div>

            <div>
              <audio controls>
                <source src="<%= rails_blob_path(file, disposition: 'attachment') %>" type="<%= file.content_type %>">
                Your browser does not support the audio element.
              </audio>
            </div>
            <div style="padding-top: 20px;">
              <%= link_to file.filename, rails_blob_path(file, disposition: 'attachment'), class: 'btn btn-primary', download: file.filename %>
            </div>

            <% else %>
            <div>
              <i class="fa-solid fa-file-alt" style="font-size: 80px;"></i>
            </div>
            <div style="padding-top: 20px;">
              <%= link_to file.filename, rails_blob_path(file, disposition: "attachment"), class: "btn btn-primary", download: file.filename %>
            </div>
          <% end %>

        </div>
      <% end %>
    <% end %>

    <div class="d-flex justify-content-center pt-5">
      <%= link_to "Back to Files", docks_path, class: "btn btn-primary mr-2" %>
      <%= button_to "Destroy File", @dock, method: :delete, class: "btn btn-danger pl-5", data: { confirm: "Are you sure?" } %>
    </div>
  </div>
</body>

app/views/layouts/_alerts.html.erb
<div class="alert alert-light alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_navbar.html.erb
<nav class="mb-1 navbar navbar-expand-lg navbar-dark bg-transparent">
<a class="navbar-brand" href="/docks/new" style="font-size: 30px;">My DropBox</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link text-white" href="/docks/new">Upload</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link text-white" href="/docks">View Files</a>
      </li>
    </ul>
    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
      <li class="nav-item dropdown">
        <a class="nav-link text-white dropdown-toggle" href="#" id="navbarNavAltMarkup" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-user-gear fa-lg"></i> Profile </a>
        <ul class="dropdown-menu" aria-labelledby="navbarNavAltMarkup">
          <li><a class="dropdown-item" href="/users/edit">Edit Profile</a></li>
          <li><a class="dropdown-item" href="/users/sign_out">Log Out</a></li>
        </ul>
      </li>
    </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DropBox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/ba9f6d5b45.js" crossorigin="anonymous"></script>
  </head>

  <body class="p-3 mb-2 bg-dark text-white">
  <% if user_signed_in? %>
  <%= render partial: "layouts/navbar"%>
<% else %>
<% end %>
  <div class="container">
  <br/>
  <% if notice %>
    <%= render 'layouts/alerts' %>

  <% end %>
      
    <%= yield %>
  </body>
</html>